/*
#Exercice 1 : Création d une base de données et de tables
    Créez une base de données nommée Entreprise.

    Créez une table nommée Client avec les champs suivants :

    Identifiant du client (clé primaire).
    Nom.
    Prénom.
    Adresse email.
    Date d inscription.
    Créez une table nommée Commande avec les champs suivants :

    Identifiant de la commande (clé primaire).
    Identifiant du client (clé étrangère).
    Date de la commande.
    Montant total.
    Insérez quelques valeurs dans chacune des tables pour tester la configuration.
*/
->
